import {Command, ResponseSender} from "./command";
import * as dreams from "./dreams.json"

export default class DreamCommand extends Command<{}> {

    constructor() {
        super(
            "dream",
            "Sends a fluffy text, generated by\"https://www.reddit.com/r/SubSimulatorGPT2/\"",
            {}
        );
    }

    protected async Run(r: ResponseSender, args: { _: string }): Promise<any> {
        const i = Math.floor(Math.random() * dreams.snippets.length);
        const d = dreams.snippets[i]
        await r.sendNotice(d)
    }

}